### ISSUE TITLE
Using ExpressJs for the backend microservices

### ISSUE THREAD

**Issue by sundriver** [atogov/RAM#4]

**Comment by paulmarrington** [comment]
I recommend we wait until it is needed. Retrofitting is not problematic and why add complexity until we need it.

**Comment by paulmarrington** [comment]
actually, only the register may need express as it acts as the reverse proxy.

**Comment by sundriver** [comment]
I am actually using RestAngular to abstract the rest interaction with the backend and RestAngular requires rest vocab on the backend, which would be easier to build with Express,
